[meta]
is_python_project = true
meta_version = "0.4.dev0" # Set by nens-meta
project_name = "nens-meta"
package_name = "nens_meta"

[tox]
default_environments = ["lint", "py311", "py312", "doc", "coverage", "dependencies", "dependencies-graph"]
minimum_coverage = "95"

[meta_workflow]
python_versions = ["3.11", "3.12"]
environments = ["lint", "coverage", "dependencies", "dependencies-graph", "TEST"]
