[meta]
is_python_project = true
meta_version = "0.1.dev0" # Set by nens-meta
project_name = "nens-meta"
package_name = "nens_meta" # Suggested by nens-meta

[tox]
default_environments = ["lint", "py311", "py312", "coverage"]
minimum_coverage = "95"

[workflow_test]
python_versions = ["3.11", "3.12"]
