"""Purpose: read and manage the .nens.toml config file
"""
import logging
from pathlib import Path

import tomlkit

from nens_meta import utils

META_FILENAME = ".nens.toml"


logger = logging.getLogger(__name__)


def nens_toml_file(project: Path) -> Path:
    return project / META_FILENAME


def create_if_missing(project: Path):
    assert not nens_toml_file(project).exists()
    nens_toml_file(project).write_text("# Initially generated by nens-meta\n")


class Config:
    """Wrapper around a project's .nens.toml

    See https://tomlkit.readthedocs.io/en/latest/quickstart/
    """

    config_file: Path
    _contents: tomlkit.TOMLDocument

    def __init__(self, project: Path):
        self.config_file = nens_toml_file(project)
        self._contents = self.read()

    def read(self) -> tomlkit.TOMLDocument:
        return tomlkit.parse(self.config_file.read_text())

    def write(self):
        utils.write_if_changed(self.config_file, tomlkit.dumps(self._contents))
