[meta]
# Version used to generate the config
meta_version = ''
# Project name (normally the name of the directory)
project_name = ''
# Whether we are a python project
is_python_project = false
# Whether we have an ansible dir
uses_ansible = false
# Name of the main python package
package_name = ''
# Minimum code coverage percentage
minimum_coverage = ''

[pyprojecttoml]

[meta_workflow]
# Python version to use for linting and so
main_python_version = '3.11'
