[meta]
# Version used to generate the config
meta_version = ''
# Project name (normally the name of the directory)
project_name = ''
# Whether we use python
uses_python = false
# Whether we have an ansible dir
uses_ansible = false

[pyprojecttoml]

[meta_workflow]
# Python version to use for linting and so
main_python_version = '3.12'
